[project]
name = "tipjar"
description = "Unique voting contract for project 06"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.tipjar]
path = "contracts/tipjar.clar"

[repl.analysis]
passes = ["check_checker"]
